language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE

install:
  - pip install coveralls
  - pip install tox
  - pip install "Django${DJANGO_VERSION}"

after_success:
  coveralls

script:
  - python setup.py test

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.11.14,<2.0"
